services:
  app:
    image: python:3.10.16-bullseye
    command: sleep infinity
    working_dir: /workspaces/Dev-Container-Compose
    volumes:
      - ..:/workspaces/Dev-Container-Compose
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local
